### ISSUE TITLE
yaml parsing of frigg settings should give a nice ouput

### ISSUE THREAD

**Issue by relekang** [frigg/frigg-runner#14]
Current status:
```
~/dev/mocco/feedhuddler(branch:master*) » frigg
frigg-runner 1.0.0
Path: /Users/rolf/dev/mocco/feedhuddler

Traceback (most recent call last):
  File "/Users/rolf/.local/bin/frigg", line 11, in <module>
    sys.exit(main())
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/frigg_runner/cli.py", line 15, in main
    Runner(**kwargs).run()
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/frigg_runner/runner.py", line 37, in __init__
    self.config = projects.build_settings(self.directory)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/frigg/projects.py", line 42, in build_settings
    settings.update(load_settings_file(path))
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/frigg/projects.py", line 24, in load_settings_file
    return yaml.load(f)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/rolf/.local/venvs/frigg-runner/lib/python2.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/Users/rolf/dev/mocco/feedhuddler/.frigg.yml", line 2, column 2
expected <block end>, but found '?'
  in "/Users/rolf/dev/mocco/feedhuddler/.frigg.yml", line 7, column 2
```

**Comment by relekang** [comment]
I think we still should show the hint from yaml about the error

**Comment by eirsyl** [comment]
Catch the ParserError and print the message?

**Comment by relekang** [comment]
Sounds like a good plan, but maybe with a more sensible message like "There is an error in your frigg settings at line x, column y"
