### ISSUE TITLE
No module named frigg_test_discovery after installing frigg-runner

### ISSUE THREAD

**Issue by oleaha** [frigg/frigg-runner#28]
Stacktrace:

```
(env)dhcp-038206:trondheimtechguide oleandreashansen$ frigg
Traceback (most recent call last):
  File "/Users/oleandreashansen/Documents/JrC/trondheimtechguide/env/bin/frigg", line 7, in <module>
    from frigg_runner.cli import main
  File "/Users/oleandreashansen/Documents/JrC/trondheimtechguide/env/lib/python2.7/site-packages/frigg_runner/cli.py", line 5, in <module>
    from frigg_runner.runner import Runner
  File "/Users/oleandreashansen/Documents/JrC/trondheimtechguide/env/lib/python2.7/site-packages/frigg_runner/runner.py", line 6, in <module>
    import frigg_settings
  File "/Users/oleandreashansen/Documents/JrC/trondheimtechguide/env/lib/python2.7/site-packages/frigg_settings/__init__.py", line 4, in <module>
    from frigg_settings.settings import build_tasks, load_settings_file, build_settings  # noqa
  File "/Users/oleandreashansen/Documents/JrC/trondheimtechguide/env/lib/python2.7/site-packages/frigg_settings/settings.py", line 4, in <module>
    from frigg_test_discovery import detect_test_tasks
ImportError: No module named frigg_test_discovery
```

**Comment by eirsyl** [comment]
You may have stopped the installation process to early. Try "pip uninstall frigg-runner && pip install frigg-runner" :smiley:

**Comment by oleaha** [comment]
Had to manually uninstall all other frigg modules to fix the problem, shouldn´t "pip uninstall frigg-runner" remove everything?

**Comment by relekang** [comment]
No, I think pip will only uninstall the packages you explicitly lists as arguments because some other package might depend on the package dependencies.
